notifications:
    email: false
language: csharp
solution: PlatformSpecific.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2
script:
    - dotnet restore
    - dotnet build
    - dotnet test test/PlatformSpecific.MSTest.Tests/PlatformSpecific.MSTest.Tests.csproj -c Release -f "netcoreapp2.2"
    - dotnet test test/PlatformSpecific.XUnit.Tests/PlatformSpecific.XUnit.Tests.csproj -c Release -f "netcoreapp2.2"
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1