version: 1.0.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
  
# prevent the double build when a branch has an active PR
skip_branch_with_pr: true

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
  
install:
  # Install repo specific stuff here
  
before_build:
  - cmd: dotnet --version

build_script:
- cmd: deploy.cmd
